name: Grass_Ultra_Proxy_V1

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-grass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Installer Cloudflare WARP
        run: |
          # Installation propre de Cloudflare WARP
          curl -fsSL https://pkg.cloudflareclient.com | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update && sudo apt-get install cloudflare-warp -y
          
          # Démarrage forcé du service
          sudo systemctl enable --now warp-svc
          sleep 5
          
          # Configuration
          sudo warp-cli --accept-tos registration new
          sudo warp-cli --accept-tos mode proxy
          sudo warp-cli --accept-tos proxy port 40001
          sudo warp-cli --accept-tos connect
          sleep 10

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les librairies
        run: |
          pip install websockets==10.4 python-socks[asyncio]

      - name: Executer le Bot
        run: python grass_bot.py
