name: Grass_Moteur_3_Ubuntu_Force
on:
  workflow_dispatch:
  schedule:
    - cron: '45 */3 * * *'

jobs:
  moteur-3:
    runs-on: ubuntu-20.04 # On utilise la version 20.04 pour avoir une 3ème IP aux USA
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configuration Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation Librairies
        run: pip install websockets==10.4 requests

      - name: Lancement du Moteur 3
        run: python grass_bot.py
